f = open('test.txt', 'r')

data = f.read().replace(" ","")
fileLength = len(data) - data.count('\n') - data.count('.')

print("Frequency of a: ",(data.count('a') / fileLength * 100, "%"))
print("Frequency of b: ",(data.count('b') / fileLength * 100, "%"))
print("Frequency of c: ",(data.count('c') / fileLength * 100, "%"))
print("Frequency of d: ",(data.count('d') / fileLength * 100, "%"))
print("Frequency of e: ",(data.count('e') / fileLength * 100, "%"))
print("Frequency of f: ",(data.count('f') / fileLength * 100, "%"))
print("Frequency of f: ",(data.count('f') / fileLength * 100, "%"))
print("Frequency of g: ",(data.count('g') / fileLength * 100, "%"))
print("Frequency of h: ",(data.count('h') / fileLength * 100, "%"))
print("Frequency of i: ",(data.count('i') / fileLength * 100, "%"))
print("Frequency of j: ",(data.count('j') / fileLength * 100, "%"))
print("Frequency of k: ",(data.count('k') / fileLength * 100, "%"))
print("Frequency of l: ",(data.count('l') / fileLength * 100, "%"))
print("Frequency of m: ",(data.count('m') / fileLength * 100, "%"))
print("Frequency of n: ",(data.count('n') / fileLength * 100, "%"))
print("Frequency of o: ",(data.count('o') / fileLength * 100, "%"))
print("Frequency of p: ",(data.count('p') / fileLength * 100, "%"))
print("Frequency of q: ",(data.count('q') / fileLength * 100, "%"))
print("Frequency of r: ",(data.count('r') / fileLength * 100, "%"))
print("Frequency of s: ",(data.count('s') / fileLength * 100, "%"))
print("Frequency of t: ",(data.count('t') / fileLength * 100, "%"))
print("Frequency of u: ",(data.count('u') / fileLength * 100, "%"))
print("Frequency of v: ",(data.count('v') / fileLength * 100, "%"))
print("Frequency of w: ",(data.count('w') / fileLength * 100, "%"))
print("Frequency of x: ",(data.count('x') / fileLength * 100, "%"))
print("Frequency of y: ",(data.count('y') / fileLength * 100, "%"))
print("Frequency of z: ",(data.count('z') / fileLength * 100, "%"))

f.close()
